baseURL = "https://shadowshell.studio/"
languageCode = "en-us"
title = "Shadow Shell Studio"

theme = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "sss game studio"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Shadow Shell Studio is preparing for its first game release."
  keywords = "game, game studio, gamedev, game dev, indie, indie game dev"
  images = [""]

[params.iconSmall]
  path = "/img/icon_small.svg"
  alt = ""

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    # title = "Shadow Shell Studio"
    # subtitle = "A simple theme for Hugo"
    # keywords = ""
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    copyright = "Shadow Shell Studio"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "shadow shell studio"
      logoHomeLink = "/"
      path = "/img/logo_black.svg"
      alt = "Shadow Shell Studio Logo"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
